services:
  database:
    image: postgis/postgis:13-3.4
    container_name: bruecke_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - bruecke_net
    deploy:
      resources:
        limits:
          memory: 512M

  cache:
    image: redis:6
    container_name: bruecke_cache
    restart: always
    networks:
      - bruecke_net
    deploy:
      resources:
        limits:
          memory: 128M

  directus:
    image: directus/directus:latest
    container_name: bruecke_cms
    restart: always
    ports:
      - "8055:8055"
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      
      # --- Ã„NDERUNG: Cache AUS ---
      CACHE_ENABLED: 'false'
      # CACHE_STORE: 'redis'
      # CACHE_HOST: 'cache'
      # CACHE_PORT: '6379'
      # ---------------------------

      STORAGE_LOCATIONS: 'local'
      STORAGE_LOCAL_ROOT: '/directus/uploads'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true' 
      WEBSOCKETS_ENABLED: 'true'
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./schema:/directus/schema
    depends_on:
      - database
      - cache
    networks:
      - bruecke_net
    deploy:
      resources:
        limits:
          memory: 1024M

networks:
  bruecke_net:
    driver: bridge
